12.0 account code shortcut
Studio73/studio73-addons pull request #30
Opened 2019-07-11 13:51 UTC by Willerr-mo

### Tarea relacionada

[4452](https://odoo.studio73.es/web#id=7685&action=2225&model=project.task&view_type=form&menu_id=2668)

### Cambios propuestos en este PR:

* Migrar account_code_shortcut a la 12

### Estado

- [X] READY :tada:
- [ ] WIP :computer::alien::exclamation:

### Como probar los cambios

### Notas adicionales

2019-07-11 14:02 UTC, Abranes requested changes
Eliminar todos los `# -*- coding: utf-8 -*-`

2019-07-11 14:02 UTC, Abranes commented on account_code_shortcut/__manifest__.py
> +# (c) 2017 Consultoría Informática Studio 73 S.L.
```suggestion
# Copyright 2017 Consultoría Informática Studio 73 S.L.
```

2019-07-12 10:01 UTC, Abranes approved these changes

2019-07-12 10:07 UTC, ioans73 commented on account_code_shortcut/__manifest__.py
> +    'description': """
```suggestion
    'summary': """
```

2019-07-12 10:08 UTC, ioans73 commented on account_code_shortcut/__manifest__.py
> +    'author': 'Consultoría Informática Studio 73 S.L.',
```suggestion
    'author': 'Studio73',
```

2019-07-12 10:09 UTC, Saphery commented on account_code_shortcut/__manifest__.py
> +    'author': 'Consultoría Informática Studio 73 S.L.',
```suggestion
    'author': 'Consultoría Informática Studio 73 S.L.',
    'author': 'Studio 73'
```

2019-07-12 10:13 UTC, merged